"""
Django settings for trenva project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'dummy_secret_key'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Add BASE_URL setting
BASE_URL = "https://trenva.store"

ALLOWED_HOSTS = ["trenva.store", "www.trenva.store"]

# ALLOWED_HOSTS = ["127.0.0.1"]

CSRF_COOKIE_SECURE = True
CSRF_TRUSTED_ORIGINS = ["https://trenva.store", "https://www.trenva.store"]

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'userauths',
    'channels',
    'core',
    'admin_dashboard.apps.AdminDashboardConfig',
    'lockdown',
    'clearcache',
    'compressor',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
    'crispy_forms',
    'crispy_bootstrap5',
    'mathfilters',
    'django_extensions',
    'django.contrib.humanize',
    'ckeditor',
    'ckeditor_uploader',
    'django_ckeditor_5',
    'taggit',
    'rest_framework',
    # 'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    "allauth.account.middleware.AccountMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'lockdown.middleware.LockdownMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.MaintenanceModeMiddleware',
    'core.tracking_middleware.VisitTrackingMiddleware',
    
]


ROOT_URLCONF = 'trenva.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'core.context.default',
                # 'core.content.cart',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.site_settings',
                'core.context_processors.vendor_status',
            ],
        },
    },
]

WSGI_APPLICATION = 'trenva.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_TZ = True


# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, "static", "js"),
#     os.path.join(BASE_DIR, "static", "libs"),
#     os.path.join(BASE_DIR, "static", "css"),
# ]

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "compressor.finders.CompressorFinder",
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# STATIC_URL = '/static/'

# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# MEDIA_URL = '/media/'

# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = '/static/'

MEDIA_URL = '/media/'

# if DEBUG:

#     STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# else:

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


JAZZMIN_SETTINGS = {
    "site_title": "Trenva",
    "site_brand": "Trenva",
    "site_header": "Trenva",
    "site_logo": "img/logo.png",
    "copyright": "Trenva | Developed by Teniteno1",
    "welcome_sign": "Trenva Online Store Backend",
    "login_logo": None,
}


LOGIN_URL = '/user/signin/'

LOGIN_REDIRECT_URL = '/ng/'
# LOGOUT_REDIRECT_URL = '/ng/'

AUTH_USER_MODEL = 'userauths.User'

CKEDITOR_UPLOAD_PATH = 'uploads/'

CKEDITOR_CONFIGS = {
    'default': {
        'codeSnippet': 'monokai',
        'toolbar': 'all',
        'extraPlugins': ', '.join(
            [
                'codesnippet',
                'widget',
                'dialog'
            ]
        ),
    }
}

# STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'


# Payment Gateway Keys
# # LIVE
PAYSTACK_SECRET = "dummy_paystack_secret_key"

PAYSTACK_SECRET_KEY = "dummy_paystack_secret_key"

PAYSTACK_PUBLIC = "dummy_paystack_public_key" 

# # TEST
# PAYSTACK_SECRET = "sk_test_652ce3c6a5951d1b74673c7106a319ff9d344a8e"

# PAYSTACK_SECRET_KEY = "sk_test_652ce3c6a5951d1b74673c7106a319ff9d344a8e"

# PAYSTACK_PUBLIC = "pk_test_579cecd36439385752906a3df24b455aaff2dd0d"

# FLUTTERWAVE_PUBLIC_KEY = "FLWPUBK_TEST-ab16d00d358c07fb4c0ab5b50d6f5b44-X"
# FLUTTERWAVE_SECRET_KEY = "FLWSECK_TEST-c7114304e64572562c9c27be69efdb9e-X"
# FLUTTERWAVE_ENCRYPTION_KEY = "FLWSECK_TEST398a072fc2fb"
# FLUTTERWAVE_BASE_URL = "https://api.flutterwave.com/v3"


# # BRT

# FLUTTERWAVE_PUBLIC_KEY = "FLWPUBK_TEST-0761882d79e49bc857bc5baf4530d16e-X"
# FLUTTERWAVE_SECRET_KEY = "FLWSECK_TEST-7ece2c05dc4d35d943297d65e03c525d-X"
# FLUTTERWAVE_ENCRYPTION_KEY = "FLWSECK_TEST137487fe92f2"
# FLUTTERWAVE_BASE_URL = "https://api.flutterwave.com/v3" 

# Logging 

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'file': {
#             'level': 'ERROR',
#             'class': 'logging.FileHandler',
#             'filename': os.path.join(BASE_DIR, 'error.log'),
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['file'],
#             'level': 'ERROR',
#             'propagate': True,
#         },
#     },
# }


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name} | {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname}: {message}",
            "style": "{",
        },
    },

    "handlers": {
        "file": {
            "level": "ERROR",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "error.log"),
            "formatter": "verbose",
        },
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },

    "loggers": {
        "django": {
            "handlers": ["file", "console"],
            "level": "ERROR",
            "propagate": True,
        },

        # Log your own app errors
        "core": {
            "handlers": ["file", "console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}

AUTHENTICATION_BACKENDS = [
    
   
    'django.contrib.auth.backends.ModelBackend',


    'allauth.account.auth_backends.AuthenticationBackend',

]




SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '869535819799-vgaoqsgg48a5a9ha34s7gkff9iahjso5.apps.googleusercontent.com',
            'secret': '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',
            'key': ''
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'}
    }
}

SITE_ID = 2


ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_LOGIN_METHODS = {'email', 'username'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
SOCIALACCOUNT_LOGIN_ON_GET = True



ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'trenva.store'
# EMAIL_PORT = 465
# EMAIL_USE_SSL = True
# EMAIL_USE_TLS = False
EMAIL_PORT = 587  # Changed from 465
EMAIL_USE_TLS = True  # Changed from False
EMAIL_USE_SSL = False  # Changed from True 
EMAIL_HOST_USER = 'noreply@trenva.store'
EMAIL_HOST_PASSWORD = 'trenva@#123'
DEFAULT_FROM_EMAIL = 'noreply@trenva.store'
SERVER_EMAIL = 'noreply@trenva.store'

LOCKDOWN_PASSWORDS = ('#%avnerT>!', 'TrenvaAk')
LOCKDOWN_URL_EXCEPTIONS = (
    r'^/ng/paystack-webhook/',
    r'^/paystack-webhook/',
    r'^/ng/webhooks/trippa/$',
)

# settings.py
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # or cached_db
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
SESSION_SAVE_EVERY_REQUEST = True  # This is important!
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


ECOMMERCE_SETTINGS = {
    'MARKUP_PERCENTAGE': 20.0,  # 20% markup on vendor price
    'PLATFORM_FEE_PERCENTAGE': 5.0,  # 5% platform fee
}


# Test/Sandbox environment

TRIPPA_API_KEY = 'tp_live_sk_j6fbwqt2y9mb5awws5h20qggt74v3fe1'  # Test key
TRIPPA_BASE_URL = 'https://sandbox-backend-o18n.onrender.com/api/v1'  # Sandbox URL
TRIPPA_WEBHOOK_SECRET = 'whsec_0f6d22db7081eb39c390cdef20681b78c12f79c2aa244a4721fc4933419c1a51'

# Trenva Warehouse Address (for Trenva products or vendor fallback)
TRENVA_PICKUP_ADDRESS = '15 Idowu Taylor Street, Victoria Island, Lagos'


# Live
# TRIPPA_API_KEY = 'tp_live_sk_cdc301c50kfpuwu46afdh69orb3jb6se'
# TRIPPA_BASE_URL = 'https://api.trippa.com/v1'  # Use this - it works!'  
# TRIPPA_WEBHOOK_SECRET = 'whsec_cad04b229c39eb84438ec3b03e701216e9de5311ba9cd47e8eb24c261d54b595' 

# 'https://api.trippa.com/v1', 


# Set this to False to temporarily disable the lockdown entirely
LOCKDOWN_ENABLED = False

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}